import './globals.css'
import Navbar from './Navbar'
import Footer from './Footer'
import { ReactQueryProvider } from './ReactQueryProvider'

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
	return (
		<ReactQueryProvider>
		<html lang="en" className="bg-white">
			<body>
				<Navbar />
				{children}
				<Footer />
			</body>
		</html>
		</ReactQueryProvider>
	)
}
