import './globals.css'
import { DM_Serif_Text, Inter } from 'next/font/google'
import Navbar from './Navbar'
import Footer from './footer'

const inter = Inter({ subsets: ['latin'] })
const serif = DM_Serif_Text({subsets: ['latin'], weight: ["400"]})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={serif.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
