# Generated by Django 4.2.6 on 2023-11-08 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigns',
            name='recipient_account',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='campaigns',
            name='recipient_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
