# Generated by Django 4.2.6 on 2023-10-23 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigns',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
