# Generated by Django 4.2.6 on 2023-10-27 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_campaigns_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Campaigns',
        ),
    ]
